.PHONY: clean
clean:
	rm -rf db.sqlite3 */__pycache__ */*/__pycache__ */migrations/0*.py

dependancies: 
	pip3 install django
	pip3 install djangorestframework-simplejwt 
	pip3 install django-multiselectfield
	pip3 install pillow
	

